Mesh file: geom.msh

Discrete Fractures :
  fracture:
    conductivity : 200
    aperture : 5e-3
    label: 1

Domain Flow Properties:
  domain:
    label: 2
    Coupled: false
    PORO: 0.2   #
    PERM: 10    # it is in milidarcies
    RTEMP: 343.15
    SWAT: 0.0   # water saturation
    PRESSURE: 2 # in atm

Domain Mechanical Properties:
  domain:
    label: 2
    Coupled: false
    GMCELL_MODEL: 0               # elastic
    GMCELL_DENSITY: 1000          # kg/m3
    GMCELL_YOUNG: 1               # young's modulus
    GMCELL_POISSON: 0.25          # poisson's ratio

Boundary Conditions:
  Faces:
    face:
      label: 1111111              # left
      type : 2
      value: [-100, 0, 0]
    face:
      label: 1111112            # right
      type : 2                  # neumann
      value: [100, 0, 0]
    face:
      label: 3333331            # bottom
      type : 1                  # dirichlet
      value: [nan, nan, 0]
    face:
      label: 3333332            # top
      type: 1                   # dirichlet
      value: [nan, nan, 0]

  Dirichlet nodes:
    node:
      location: "near(X, -100, Y, 0, Z, 0, 1e-2)"
      # coord: [-100, 0, 0]
      value: [nan, 0 , nan]
    node:
      location: "near(X, 100, Y, 0, Z, 0, 1e-2)"
      # coord: [100, 0, 0]
      value : [nan, 0 , nan]
    node:
      location: "near(X, 0, Y, 100, Z, 0, 1e-2)"
      # coord : [0, 100, 0]
      value : [0, nan , nan]
    node:
      location: "near(X, 0, Y, -100, Z, 0, 1e-2)"
      # coord : [0, -100, 0]
      value : [0, nan , nan]

